// resources/js/Pages/Admin/Reports/ReportTypes/utils/helpers.tsx
import React from 'react';
import { 
    AlertTriangle,
    AlertCircle,
    Volume2,
    Trash2,
    PawPrint,
    Droplets,
    Zap,
    Map,
    ShieldAlert,
    Users,
    HeartPulse,
    Building,
    Car,
    Waves,
    Store,
    FileText,
    Image,
    Clock,
    HelpCircle,
    Sparkles,
    Target,
    BarChart,
    ListChecks,
    Activity,
    Settings,
    UserCog,
    CheckCircle,
    XCircle,
    Clock4,
    Award,
    Tag,
    Hash,
    File,
    Eye,
    Download,
    Printer,
    Calendar,
    Shield,
    Globe,
    User,
    Mail,
    Phone,
    MapPin,
    Layers,
    AlertOctagon,
    Bell,
    BellRing,
    Flame,
    FlameKindling,
    Gauge,
    GanttChart,
    GanttChartSquare,
    GanttChartSquareIcon,
    Gem,
    Gift,
    GitBranch,
    GitCommit,
    GitCompare,
    GitFork,
    GitGraph,
    GitMerge,
    GitPullRequest,
    Globe2,
    Hammer,
    Hand,
    HandHeart,
    HandHelping,
    HandMetal,
    HandPlatter,
    HardHat,
    HardDrive,
    HardDriveDownload,
    HardDriveUpload,
    Headphones,
    Headset,
    Heart,
    HeartCrack,
    HeartHandshake,
    HeartOff,
    HeartPulse as HeartPulseIcon,
    HelpCircle as HelpCircleIcon,
    History,
    Home,
    HomeIcon,
    Hourglass,
    IceCream,
    IceCream2,
    IdCard,
    Image as ImageIcon,
    Images,
    Inbox,
    Indent,
    IndianRupee,
    Infinity,
    Info,
    Inspect,
    Instagram,
    Italic,
    IterationCcw,
    IterationCw,
    JapaneseYen,
    Joystick,
    Kanban,
    KanbanSquare,
    KanbanSquareIcon,
    Key,
    KeyRound,
    KeySquare,
    Keyboard,
    Lamp,
    LampCeiling,
    LampDesk,
    LampFloor,
    LampWallDown,
    LampWallUp,
    LandPlot,
    Landmark,
    Languages,
    Laptop,
    Laptop2,
    Lasso,
    LassoSelect,
    Laugh,
    Layers2,
    Layers3,
    Layout,
    LayoutDashboard,
    LayoutGrid,
    LayoutList,
    LayoutPanelLeft,
    LayoutPanelTop,
    LayoutTemplate,
    Leaf,
    LeafyGreen,
    Library,
    LifeBuoy,
    Ligature,
    Lightbulb,
    LightbulbOff,
    LineChart,
    Link,
    Link2,
    Link2Off,
    LinkIcon,
    List,
    ListChecks as ListChecksIcon,
    ListEnd,
    ListFilter,
    ListMinus,
    ListMusic,
    ListOrdered,
    ListPlus,
    ListRestart,
    ListStart,
    ListTodo,
    ListTree,
    Loader,
    Loader2,
    Locate,
    LocateFixed,
    LocateOff,
    Lock,
    LockKeyhole,
    LockKeyholeOpen,
    LockOpen,
    LogIn,
    LogOut,
    Luggage,
    Magnet,
    Mail as MailIcon,
    MailCheck,
    MailMinus,
    MailOpen,
    MailPlus,
    MailQuestion,
    MailSearch,
    MailWarning,
    MailX,
    Mailbox,
    Mails,
    Map as MapIcon,
    MapPin as MapPinIcon,
    MapPinOff,
    MapPinned,
    Martini,
    Maximize,
    Maximize2,
    Medal,
    Megaphone,
    MegaphoneOff,
    Meh,
    MemoryStick,
    Menu,
    Merge,
    MessageCircle,
    MessageCircleCode,
    MessageCircleDashed,
    MessageCircleHeart,
    MessageCircleMore,
    MessageCircleOff,
    MessageCirclePlus,
    MessageCircleQuestion,
    MessageCircleReply,
    MessageCircleWarning,
    MessageCircleX,
    MessageSquare,
    MessageSquareCode,
    MessageSquareDashed,
    MessageSquareDiff,
    MessageSquareDot,
    MessageSquareHeart,
    MessageSquareMore,
    MessageSquareOff,
    MessageSquarePlus,
    MessageSquareQuote,
    MessageSquareReply,
    MessageSquareShare,
    MessageSquareText,
    MessageSquareWarning,
    MessageSquareX,
    MessagesSquare,
    Mic,
    Mic2,
    MicOff,
    Microscope,
    Microwave,
    Milestone,
    Milk,
    MilkOff,
    Minimize,
    Minimize2,
    Minus,
    MinusCircle,
    MinusSquare,
    Monitor,
    MonitorCheck,
    MonitorDot,
    MonitorDown,
    MonitorOff,
    MonitorPause,
    MonitorPlay,
    MonitorSmartphone,
    MonitorSpeaker,
    MonitorStop,
    MonitorUp,
    Moon,
    MoonStar,
    MoreHorizontal,
    MoreVertical,
    Mountain,
    MountainSnow,
    Mouse,
    MouseOff,
    MousePointer,
    MousePointer2,
    MousePointerClick,
    MousePointerSquareDashed,
    Move,
    Move3d,
    MoveDiagonal,
    MoveDiagonal2,
    MoveDown,
    MoveDownLeft,
    MoveDownRight,
    MoveHorizontal,
    MoveLeft,
    MoveRight,
    MoveUp,
    MoveUpLeft,
    MoveUpRight,
    MoveVertical,
    Music,
    Music2,
    Music3,
    Music4,
    Navigation,
    Navigation2,
    Navigation2Off,
    NavigationOff,
    Network,
    Newspaper,
    Nfc,
    Notebook,
    NotebookPen,
    NotebookTabs,
    NotebookText,
    NotepadText,
    NotepadTextDashed,
    Nut,
    NutOff,
    Octagon,
    OctagonAlert,
    OctagonMinus,
    OctagonPause,
    OctagonX,
    Omega,
    Option,
    Orbit,
    Origami,
    Outdent,
    Package,
    Package2,
    PackageCheck,
    PackageMinus,
    PackageOpen,
    PackagePlus,
    PackageSearch,
    PackageX,
    PaintBucket,
    PaintRoller,
    Paintbrush,
    Paintbrush2,
    Palette,
    Palmtree,
    PanelBottom,
    PanelBottomClose,
    PanelBottomDashed,
    PanelBottomOpen,
    PanelLeft,
    PanelLeftClose,
    PanelLeftDashed,
    PanelLeftOpen,
    PanelRight,
    PanelRightClose,
    PanelRightDashed,
    PanelRightOpen,
    PanelTop,
    PanelTopClose,
    PanelTopDashed,
    PanelTopOpen,
    PanelsLeftBottom,
    PanelsRightBottom,
    PanelsTopLeft,
    Paperclip,
    Parentheses,
    ParkingCircle,
    ParkingCircleOff,
    ParkingMeter,
    ParkingSquare,
    ParkingSquareOff,
    PartyPopper,
    Pause,
    PauseCircle,
    PauseOctagon,
    PawPrint as PawPrintIcon,
    PcCase,
    Pen,
    PenLine,
    PenOff,
    PenTool,
    Pencil,
    PencilLine,
    PencilOff,
    PencilRuler,
    Pentagon,
    Percent,
    PersonStanding,
    PhilippinePeso,
    Phone as PhoneIcon,
    PhoneCall,
    PhoneForwarded,
    PhoneIncoming,
    PhoneMissed,
    PhoneOff,
    PhoneOutgoing,
    Pi,
    Piano,
    Pickaxe,
    PictureInPicture,
    PictureInPicture2,
    PieChart,
    PiggyBank,
    Pilcrow,
    PilcrowLeft,
    PilcrowRight,
    Pill,
    Pin,
    PinOff,
    Pipette,
    Pizza,
    Plane,
    PlaneLanding,
    PlaneTakeoff,
    Play,
    PlayCircle,
    PlaySquare,
    Plug,
    Plug2,
    PlugZap,
    PlugZap2,
    Plus as PlusIcon,
    PlusCircle,
    PlusSquare,
    Pocket,
    PocketKnife,
    Podcast,
    Pointer,
    PointerOff,
    Popcorn,
    Popsicle,
    PoundSterling,
    Power,
    PowerOff,
    Presentation,
    Printer as PrinterIcon,
    PrinterCheck,
    Projector,
    Proportions,
    Puzzle,
    Pyramid,
    QrCode,
    Quote,
    Rabbit,
    Radar,
    Radiation,
    Radical,
    Radio,
    RadioReceiver,
    RadioTower,
    Radius,
    RailSymbol,
    Rainbow,
    Rat,
    Ratio,
    Receipt,
    ReceiptCent,
    ReceiptEuro,
    ReceiptIndianRupee,
    ReceiptJapaneseYen,
    ReceiptPoundSterling,
    ReceiptRussianRuble,
    ReceiptSwissFranc,
    ReceiptText,
    RectangleEllipsis,
    RectangleHorizontal,
    RectangleVertical,
    Recycle,
    Redo,
    Redo2,
    RedoDot,
    RefreshCcw,
    RefreshCcwDot,
    RefreshCw as RefreshCwIcon,
    RefreshCwOff,
    Refrigerator,
    Regex,
    RemoveFormatting,
    Repeat,
    Repeat1,
    Repeat2,
    Replace,
    ReplaceAll,
    Reply,
    ReplyAll,
    Rewind,
    Ribbon,
    Rocket,
    RockingChair,
    RollerCoaster,
    Rotate3d,
    RotateCcw,
    RotateCw,
    Route,
    Router,
    Rows,
    Rows2,
    Rows3,
    Rows4,
    Rss,
    Ruler,
    RussianRuble,
    Sailboat,
    Salad,
    Sandwich,
    Satellite,
    SatelliteDish,
    Save,
    SaveAll,
    SaveOff,
    Scale,
    Scale3d,
    Scaling,
    Scan,
    ScanBarcode,
    ScanEye,
    ScanFace,
    ScanLine,
    ScanQrCode,
    ScanSearch,
    ScanText,
    ScatterChart,
    School,
    School2,
    Scissors,
    ScissorsLineDashed,
    ScreenShare,
    ScreenShareOff,
    Scroll,
    ScrollText,
    Search as SearchIcon,
    SearchCheck,
    SearchCode,
    SearchSlash,
    SearchX,
    Section,
    Send,
    SendHorizontal,
    SendToBack,
    SeparatorHorizontal,
    SeparatorVertical,
    Server,
    ServerCog,
    ServerCrash,
    ServerOff,
    Settings as SettingsIcon,
    Settings2,
    Shapes,
    Share,
    Share2,
    Sheet,
    Shell,
    Shield as ShieldIcon,
    ShieldAlert as ShieldAlertIcon,
    ShieldBan,
    ShieldCheck as ShieldCheckIcon,
    ShieldEllipsis,
    ShieldHalf,
    ShieldMinus,
    ShieldOff,
    ShieldPlus,
    ShieldQuestion,
    ShieldX,
    Ship,
    ShipWheel,
    Shirt,
    ShoppingBag,
    ShoppingBasket,
    ShoppingCart,
    Shovel,
    ShowerHead,
    Shrink,
    Shrub,
    Shuffle,
    Sigma,
    Signal,
    SignalHigh,
    SignalLow,
    SignalMedium,
    SignalZero,
    Signature,
    Signpost,
    SignpostBig,
    Siren,
    SkipBack,
    SkipForward,
    Skull,
    Slack,
    Slash,
    Slice,
    SlidersHorizontal,
    SlidersVertical,
    Smartphone,
    SmartphoneCharging,
    SmartphoneNfc,
    Smile,
    SmilePlus,
    Snail,
    Snowflake,
    Sofa,
    SortAsc,
    SortDesc,
    Soup,
    Space,
    Spade,
    Sparkle,
    Sparkles as SparklesIcon,
    Speaker,
    Speech,
    SpellCheck,
    SpellCheck2,
    Spline,
    Split,
    SprayCan,
    Sprout,
    Square,
    SquareActivity,
    SquareArrowDown,
    SquareArrowDownLeft,
    SquareArrowDownRight,
    SquareArrowLeft,
    SquareArrowOutDownLeft,
    SquareArrowOutDownRight,
    SquareArrowOutUpLeft,
    SquareArrowOutUpRight,
    SquareArrowRight,
    SquareArrowUp,
    SquareArrowUpLeft,
    SquareArrowUpRight,
    SquareAsterisk,
    SquareBottomDashedScissors,
    SquareCheck,
    SquareCheckBig,
    SquareChevronDown,
    SquareChevronLeft,
    SquareChevronRight,
    SquareChevronUp,
    SquareCode,
    SquareDashed,
    SquareDashedBottom,
    SquareDashedBottomCode,
    SquareDashedKanban,
    SquareDashedMousePointer,
    SquareDivide,
    SquareDot,
    SquareEqual,
    SquareFunction,
    SquareKanban,
    SquareLibrary,
    SquareM,
    SquareMenu,
    SquareMinus,
    SquareMousePointer,
    SquareParking,
    SquareParkingOff,
    SquarePen,
    SquarePercent,
    SquarePi,
    SquarePilcrow,
    SquarePlay,
    SquarePlus,
    SquarePower,
    SquareRadical,
    SquareScissors,
    SquareSigma,
    SquareSlash,
    SquareSplitHorizontal,
    SquareSplitVertical,
    SquareStack,
    SquareTerminal,
    SquareUser,
    SquareUserRound,
    SquareX,
    Squircle,
    Squirrel,
    Stamp,
    Star,
    StarHalf,
    StarOff,
    StepBack,
    StepForward,
    Stethoscope,
    Sticker,
    StickyNote,
    StopCircle,
    Store as StoreIcon,
    StretchHorizontal,
    StretchVertical,
    Strikethrough,
    Subscript,
    Sun,
    SunDim,
    SunMedium,
    SunMoon,
    SunSnow,
    Sunrise,
    Sunset,
    Superscript,
    SwissFranc,
    SwitchCamera,
    Sword,
    Swords,
    Syringe,
    Table,
    Table2,
    TableCellsMerge,
    TableCellsSplit,
    TableColumnsSplit,
    TableOfContents,
    TableProperties,
    TableRowsSplit,
    Tablet,
    TabletSmartphone,
    Tablets,
    Tag as TagIcon,
    Tags,
    Tally1,
    Tally2,
    Tally3,
    Tally4,
    Tally5,
    Tangent,
    Target as TargetIcon,
    Telescope,
    Tent,
    TentTree,
    Terminal,
    TestTube,
    TestTube2,
    TestTubes,
    Text,
    TextCursor,
    TextCursorInput,
    TextQuote,
    TextSearch,
    TextSelect,
    Theater,
    Thermometer,
    ThermometerSnowflake,
    ThermometerSun,
    ThumbsDown,
    ThumbsUp,
    Ticket,
    TicketCheck,
    TicketMinus,
    TicketPercent,
    TicketPlus,
    TicketSlash,
    TicketX,
    ToggleLeft,
    ToggleRight,
    Toilet,
    Tornado,
    TowerControl,
    ToyBrick,
    Tractor,
    TrafficCone,
    Train,
    TrainFront,
    TrainFrontTunnel,
    TrainTrack,
    TramFront,
    Trash,
    Trash2 as Trash2Icon,
    TreeDeciduous,
    TreePalm,
    TreePine,
    Trees,
    Trello,
    TrendingDown,
    TrendingUp,
    Triangle,
    TriangleAlert,
    TriangleRight,
    Trophy,
    Truck,
    Turtle,
    Tv,
    Tv2,
    Twitch,
    Twitter,
    Type,
    Umbrella,
    UmbrellaOff,
    Underline,
    Undo,
    Undo2,
    UndoDot,
    UnfoldHorizontal,
    UnfoldVertical,
    Ungroup,
    Unlink,
    Unlink2,
    Unlock,
    Unplug,
    Upload,
    Usb,
    User as UserIcon,
    UserCheck,
    UserCog as UserCogIcon,
    UserMinus,
    UserPlus,
    UserRound,
    UserRoundCheck,
    UserRoundCog,
    UserRoundMinus,
    UserRoundPlus,
    UserRoundSearch,
    UserRoundX,
    UserSearch,
    UserX,
    Users as UsersIcon,
    UsersRound,
    Utensils,
    UtensilsCrossed,
    UtilityPole,
    Variable,
    Vault,
    Vegan,
    VenetianMask,
    Verified,
    Vibrate,
    VibrateOff,
    Video,
    VideoOff,
    Videotape,
    View,
    Voicemail,
    Volume,
    Volume1,
    Volume2 as Volume2Icon,
    VolumeX,
    Vote,
    Wallet,
    WalletCards,
    WalletMinimal,
    Wallpaper,
    Wand,
    WandSparkles,
    Warehouse,
    WashingMachine,
    Watch,
    Waves as WavesIcon,
    Waypoints,
    Webcam,
    Webhook,
    WebhookOff,
    Weight,
    Wheat,
    WheatOff,
    WholeWord,
    Wifi,
    WifiHigh,
    WifiLow,
    WifiOff,
    WifiZero,
    Wind,
    Wine,
    WineOff,
    Workflow,
    Worm,
    WrapText,
    Wrench,
    X as XIcon,
    XCircle as XCircleIcon,
    XOctagon,
    XSquare,
    Youtube,
    Zap as ZapIcon,
    ZapOff,
    ZoomIn,
    ZoomOut,
} from 'lucide-react';

export const getIconComponent = (iconName: string) => {
    const icons: Record<string, any> = {
        'alert-triangle': AlertTriangle,
        'alert-circle': AlertCircle,
        'alert-octagon': AlertOctagon,
        'volume-2': Volume2,
        'trash-2': Trash2,
        'paw-print': PawPrint,
        'droplets': Droplets,
        'zap': Zap,
        'road': Map,
        'shield-alert': ShieldAlert,
        'users': Users,
        'heart-pulse': HeartPulse,
        'building': Building,
        'car': Car,
        'waves': Waves,
        'store': Store,
        'file-text': FileText,
        'image': Image,
        'clock': Clock,
        'help-circle': HelpCircle,
        'sparkles': Sparkles,
        'target': Target,
        'bar-chart': BarChart,
        'list-checks': ListChecks,
        'activity': Activity,
        'settings': Settings,
        'user-cog': UserCog,
    };
    return icons[iconName] || AlertCircle;
};

export const getPriorityIcon = (level: number) => {
    switch(level) {
        case 1: return <Zap className="h-4 w-4 text-red-600 dark:text-red-400" />;
        case 2: return <AlertTriangle className="h-4 w-4 text-orange-600 dark:text-orange-400" />;
        case 3: return <Clock className="h-4 w-4 text-yellow-600 dark:text-yellow-400" />;
        case 4: return <Clock4 className="h-4 w-4 text-green-600 dark:text-green-400" />;
        default: return <Clock className="h-4 w-4" />;
    }
};

export const getStatusBadge = (isActive: boolean) => {
    return isActive ? 'Active' : 'Inactive';
};

export const getStatusIcon = (isActive: boolean) => {
    return isActive ? 
        <CheckCircle className="h-5 w-5 text-green-500 dark:text-green-400" /> : 
        <XCircle className="h-5 w-5 text-gray-500 dark:text-gray-400" />;
};

export const getStatusVariant = (isActive: boolean) => {
    return isActive ? 'default' : 'secondary';
};

export const getColorClass = (color: string) => {
    switch (color) {
        case 'blue': return 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300';
        case 'green': return 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300';
        case 'purple': return 'bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300';
        case 'amber': return 'bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300';
        case 'red': return 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300';
        case 'orange': return 'bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-300';
        default: return 'bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-300';
    }
};

export const getPriorityColor = (level: number): string => {
    switch(level) {
        case 1: return 'red';
        case 2: return 'orange';
        case 3: return 'amber';
        case 4: return 'green';
        default: return 'gray';
    }
};

export const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
    });
};

export const formatDateTime = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
    });
};

export const formatShortDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    });
};

export const formatTimeAgo = (dateString: string) => {
    const date = new Date(dateString);
    const now = new Date();
    const diffInSeconds = Math.floor((now.getTime() - date.getTime()) / 1000);
    
    if (diffInSeconds < 60) return 'just now';
    if (diffInSeconds < 3600) return `${Math.floor(diffInSeconds / 60)} minutes ago`;
    if (diffInSeconds < 86400) return `${Math.floor(diffInSeconds / 3600)} hours ago`;
    if (diffInSeconds < 604800) return `${Math.floor(diffInSeconds / 86400)} days ago`;
    return formatShortDate(dateString);
};

export const isNew = (createdAt: string) => {
    const created = new Date(createdAt);
    const now = new Date();
    const diffDays = Math.floor((now.getTime() - created.getTime()) / (1000 * 60 * 60 * 24));
    return diffDays < 7;
};