<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DiscountRuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $discounts = [
            // Senior Citizen Discounts
            [
                'code' => 'SENIOR_20',
                'name' => 'Senior Citizen Discount - 20%',
                'description' => 'Standard 20% discount for senior citizens (60 years old and above) on purchased goods and services',
                'discount_type' => 'percentage',
                'value_type' => 'percentage',
                'discount_value' => 20.00,
                'maximum_discount_amount' => null,
                'minimum_purchase_amount' => null,
                'priority' => 100,
                'requires_verification' => 1,
                'verification_document' => 'Senior Citizen ID, OSCA ID',
                'applicable_to' => 'resident',
                'applicable_puroks' => json_encode(['All Puroks']),
                'stackable' => 0,
                'exclusive_with' => json_encode(['pwd_discount', 'solo_parent']),
                'effective_date' => Carbon::now()->subDays(30),
                'expiry_date' => null,
                'is_active' => 1,
                'sort_order' => 1,
                'notes' => 'Based on Expanded Senior Citizens Act of 2010 (RA 9994)',
            ],
            [
                'code' => 'SENIOR_5_POINTS',
                'name' => 'Senior Citizen Points Program',
                'description' => 'Accumulate points for every purchase that can be redeemed for barangay services',
                'discount_type' => 'fixed',
                'value_type' => 'fixed',
                'discount_value' => 0.00,
                'maximum_discount_amount' => 500.00,
                'minimum_purchase_amount' => 100.00,
                'priority' => 90,
                'requires_verification' => 1,
                'verification_document' => 'Senior Citizen ID',
                'applicable_to' => 'resident',
                'applicable_puroks' => json_encode(['All Puroks']),
                'stackable' => 1,
                'exclusive_with' => null,
                'effective_date' => Carbon::now()->subDays(15),
                'expiry_date' => null,
                'is_active' => 1,
                'sort_order' => 2,
                'notes' => 'Loyalty points program for senior citizens',
            ],

            // PWD Discounts
            [
                'code' => 'PWD_20',
                'name' => 'PWD Discount - 20%',
                'description' => '20% discount for Persons with Disability (PWD) on basic necessities and services',
                'discount_type' => 'percentage',
                'value_type' => 'percentage',
                'discount_value' => 20.00,
                'maximum_discount_amount' => null,
                'minimum_purchase_amount' => null,
                'priority' => 95,
                'requires_verification' => 1,
                'verification_document' => 'PWD ID',
                'applicable_to' => 'resident',
                'applicable_puroks' => json_encode(['All Puroks']),
                'stackable' => 0,
                'exclusive_with' => json_encode(['senior_discount', 'solo_parent']),
                'effective_date' => Carbon::now()->subDays(30),
                'expiry_date' => null,
                'is_active' => 1,
                'sort_order' => 3,
                'notes' => 'Based on Magna Carta for Persons with Disability (RA 10754)',
            ],

            // Solo Parent Discount
            [
                'code' => 'SOLO_PARENT_10',
                'name' => 'Solo Parent Discount',
                'description' => '10% discount on purchases of basic necessities for solo parents',
                'discount_type' => 'percentage',
                'value_type' => 'percentage',
                'discount_value' => 10.00,
                'maximum_discount_amount' => 500.00,
                'minimum_purchase_amount' => 100.00,
                'priority' => 85,
                'requires_verification' => 1,
                'verification_document' => 'Solo Parent ID',
                'applicable_to' => 'resident',
                'applicable_puroks' => json_encode(['All Puroks']),
                'stackable' => 0,
                'exclusive_with' => json_encode(['senior_discount', 'pwd_discount']),
                'effective_date' => Carbon::now()->subDays(20),
                'expiry_date' => null,
                'is_active' => 1,
                'sort_order' => 4,
                'notes' => 'Based on Solo Parents Welfare Act (RA 8972)',
            ],

            // Student Discounts
            [
                'code' => 'STUDENT_10',
                'name' => 'Student Discount',
                'description' => '10% discount for students on school supplies and related items',
                'discount_type' => 'percentage',
                'value_type' => 'percentage',
                'discount_value' => 10.00,
                'maximum_discount_amount' => 300.00,
                'minimum_purchase_amount' => 50.00,
                'priority' => 80,
                'requires_verification' => 1,
                'verification_document' => 'School ID, Registration Form',
                'applicable_to' => 'student',
                'applicable_puroks' => json_encode(['All Puroks']),
                'stackable' => 0,
                'exclusive_with' => null,
                'effective_date' => Carbon::now()->subDays(45),
                'expiry_date' => Carbon::now()->addMonths(6),
                'is_active' => 1,
                'sort_order' => 5,
                'notes' => 'Back-to-school promo for students',
            ],

            // Purok-Specific Discounts
            [
                'code' => 'PUROK_A_5',
                'name' => 'Purok A Residents Discount',
                'description' => 'Special 5% discount for Purok A residents during fiesta celebration',
                'discount_type' => 'percentage',
                'value_type' => 'percentage',
                'discount_value' => 5.00,
                'maximum_discount_amount' => 200.00,
                'minimum_purchase_amount' => 50.00,
                'priority' => 60,
                'requires_verification' => 1,
                'verification_document' => 'Barangay Clearance, Valid ID',
                'applicable_to' => 'resident',
                'applicable_puroks' => json_encode(['Purok A']),
                'stackable' => 0,
                'exclusive_with' => null,
                'effective_date' => Carbon::now(),
                'expiry_date' => Carbon::now()->addDays(30),
                'is_active' => 1,
                'sort_order' => 6,
                'notes' => 'Fiesta celebration promo for Purok A',
            ],

            // Loyalty/Bulk Purchase Discount
            [
                'code' => 'BULK_PURCHASE_15',
                'name' => 'Bulk Purchase Discount',
                'description' => '15% discount on bulk purchases (minimum of 5 items)',
                'discount_type' => 'percentage',
                'value_type' => 'percentage',
                'discount_value' => 15.00,
                'maximum_discount_amount' => 1000.00,
                'minimum_purchase_amount' => 1000.00,
                'priority' => 70,
                'requires_verification' => 0,
                'verification_document' => null,
                'applicable_to' => 'all',
                'applicable_puroks' => json_encode(['All Puroks']),
                'stackable' => 1,
                'exclusive_with' => null,
                'effective_date' => Carbon::now(),
                'expiry_date' => null,
                'is_active' => 1,
                'sort_order' => 7,
                'notes' => 'Bulk purchase incentive for all customers',
            ],

            // Early Bird Discount
            [
                'code' => 'EARLY_BIRD_10',
                'name' => 'Early Bird Special',
                'description' => '10% discount for purchases made before 8:00 AM',
                'discount_type' => 'percentage',
                'value_type' => 'percentage',
                'discount_value' => 10.00,
                'maximum_discount_amount' => 100.00,
                'minimum_purchase_amount' => 100.00,
                'priority' => 75,
                'requires_verification' => 0,
                'verification_document' => null,
                'applicable_to' => 'all',
                'applicable_puroks' => json_encode(['All Puroks']),
                'stackable' => 1,
                'exclusive_with' => null,
                'effective_date' => Carbon::now(),
                'expiry_date' => null,
                'is_active' => 1,
                'sort_order' => 8,
                'notes' => 'Early morning shopping incentive',
            ],

            // Barangay Health Worker Discount
            [
                'code' => 'BHW_10',
                'name' => 'Barangay Health Worker Discount',
                'description' => '10% discount for active Barangay Health Workers',
                'discount_type' => 'percentage',
                'value_type' => 'percentage',
                'discount_value' => 10.00,
                'maximum_discount_amount' => 300.00,
                'minimum_purchase_amount' => 100.00,
                'priority' => 88,
                'requires_verification' => 1,
                'verification_document' => 'BHW ID, Certificate of Appointment',
                'applicable_to' => 'employee',
                'applicable_puroks' => json_encode(['All Puroks']),
                'stackable' => 0,
                'exclusive_with' => json_encode(['senior_discount', 'pwd_discount']),
                'effective_date' => Carbon::now()->subDays(10),
                'expiry_date' => null,
                'is_active' => 1,
                'sort_order' => 9,
                'notes' => 'Appreciation discount for BHW volunteers',
            ],

            // Barangay Tanod Discount
            [
                'code' => 'TANOD_10',
                'name' => 'Barangay Tanod Discount',
                'description' => '10% discount for active Barangay Tanod members',
                'discount_type' => 'percentage',
                'value_type' => 'percentage',
                'discount_value' => 10.00,
                'maximum_discount_amount' => 300.00,
                'minimum_purchase_amount' => 100.00,
                'priority' => 88,
                'requires_verification' => 1,
                'verification_document' => 'Tanod ID',
                'applicable_to' => 'employee',
                'applicable_puroks' => json_encode(['All Puroks']),
                'stackable' => 0,
                'exclusive_with' => json_encode(['senior_discount', 'pwd_discount']),
                'effective_date' => Carbon::now()->subDays(5),
                'expiry_date' => null,
                'is_active' => 1,
                'sort_order' => 10,
                'notes' => 'Appreciation discount for Barangay Tanod',
            ],

            // Seasonal/Holiday Discounts
            [
                'code' => 'CHRISTMAS_15',
                'name' => 'Christmas Season Discount',
                'description' => '15% discount on all purchases during Christmas season',
                'discount_type' => 'percentage',
                'value_type' => 'percentage',
                'discount_value' => 15.00,
                'maximum_discount_amount' => 500.00,
                'minimum_purchase_amount' => 200.00,
                'priority' => 65,
                'requires_verification' => 0,
                'verification_document' => null,
                'applicable_to' => 'all',
                'applicable_puroks' => json_encode(['All Puroks']),
                'stackable' => 0,
                'exclusive_with' => null,
                'effective_date' => Carbon::create(null, 12, 1, 0, 0, 0), // Dec 1
                'expiry_date' => Carbon::create(null, 12, 31, 23, 59, 59), // Dec 31
                'is_active' => 1,
                'sort_order' => 11,
                'notes' => 'Christmas season promo',
            ],
            [
                'code' => 'FIESTA_20',
                'name' => 'Barangay Fiesta Discount',
                'description' => 'Special 20% discount during barangay fiesta celebration',
                'discount_type' => 'percentage',
                'value_type' => 'percentage',
                'discount_value' => 20.00,
                'maximum_discount_amount' => 1000.00,
                'minimum_purchase_amount' => 100.00,
                'priority' => 95,
                'requires_verification' => 1,
                'verification_document' => 'Barangay Clearance',
                'applicable_to' => 'resident',
                'applicable_puroks' => json_encode(['All Puroks']),
                'stackable' => 0,
                'exclusive_with' => json_encode(['senior_discount', 'pwd_discount']),
                'effective_date' => Carbon::create(null, 5, 15, 0, 0, 0), // Example fiesta date
                'expiry_date' => Carbon::create(null, 5, 15, 23, 59, 59),
                'is_active' => 1,
                'sort_order' => 12,
                'notes' => 'Barangay fiesta special discount',
            ],

            // First Time Customer
            [
                'code' => 'FIRST_TIME_10',
                'name' => 'First Time Customer Discount',
                'description' => '10% discount for first-time customers',
                'discount_type' => 'percentage',
                'value_type' => 'percentage',
                'discount_value' => 10.00,
                'maximum_discount_amount' => 200.00,
                'minimum_purchase_amount' => 100.00,
                'priority' => 50,
                'requires_verification' => 1,
                'verification_document' => 'Valid ID, Barangay Clearance',
                'applicable_to' => 'non-resident',
                'applicable_puroks' => json_encode(['All Puroks']),
                'stackable' => 0,
                'exclusive_with' => null,
                'effective_date' => Carbon::now(),
                'expiry_date' => null,
                'is_active' => 1,
                'sort_order' => 13,
                'notes' => 'Welcome discount for new customers',
            ],
        ];

        // Insert all discount rules
        foreach ($discounts as $discount) {
            DB::table('discount_rules')->insert([
                'code' => $discount['code'],
                'name' => $discount['name'],
                'description' => $discount['description'],
                'discount_type' => $discount['discount_type'],
                'value_type' => $discount['value_type'],
                'discount_value' => $discount['discount_value'],
                'maximum_discount_amount' => $discount['maximum_discount_amount'],
                'minimum_purchase_amount' => $discount['minimum_purchase_amount'],
                'priority' => $discount['priority'],
                'requires_verification' => $discount['requires_verification'],
                'verification_document' => $discount['verification_document'],
                'applicable_to' => $discount['applicable_to'],
                'applicable_puroks' => $discount['applicable_puroks'],
                'stackable' => $discount['stackable'],
                'exclusive_with' => $discount['exclusive_with'],
                'effective_date' => $discount['effective_date'],
                'expiry_date' => $discount['expiry_date'],
                'is_active' => $discount['is_active'],
                'sort_order' => $discount['sort_order'],
                'notes' => $discount['notes'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}