<?php

namespace Database\Seeders;

use App\Models\DocumentType;
use Illuminate\Database\Seeder;

class DocumentTypesSeeder extends Seeder
{
    public function run(): void
    {
        $documentTypes = [
            // IDENTIFICATION DOCUMENTS
            [
                'name' => 'Valid ID (Government Issued)',
                'code' => 'valid_id_gov',
                'description' => 'Any valid government-issued identification card (Passport, Driver\'s License, PRC ID, SSS ID, PhilHealth ID, Postal ID, Voter\'s ID)',
                'category' => 'identification',
                'is_required' => true,
                'sort_order' => 1,
                'accepted_formats' => ['jpg', 'jpeg', 'png', 'pdf'],
                'max_file_size' => 2048,
            ],
            [
                'name' => 'Barangay ID',
                'code' => 'barangay_id',
                'description' => 'Barangay Identification Card',
                'category' => 'identification',
                'is_required' => false,
                'sort_order' => 2,
                'accepted_formats' => ['jpg', 'jpeg', 'png', 'pdf'],
                'max_file_size' => 2048,
            ],
            [
                'name' => 'Philippine Passport',
                'code' => 'passport',
                'description' => 'Valid Philippine Passport (Bio page)',
                'category' => 'identification',
                'is_required' => false,
                'sort_order' => 3,
                'accepted_formats' => ['jpg', 'jpeg', 'png', 'pdf'],
                'max_file_size' => 2048,
            ],
            [
                'name' => 'Driver\'s License',
                'code' => 'drivers_license',
                'description' => 'Valid Driver\'s License (LTO)',
                'category' => 'identification',
                'is_required' => false,
                'sort_order' => 4,
                'accepted_formats' => ['jpg', 'jpeg', 'png', 'pdf'],
                'max_file_size' => 2048,
            ],
            [
                'name' => 'Voter\'s ID',
                'code' => 'voters_id',
                'description' => 'COMELEC Voter\'s Identification Card',
                'category' => 'identification',
                'is_required' => false,
                'sort_order' => 5,
                'accepted_formats' => ['jpg', 'jpeg', 'png', 'pdf'],
                'max_file_size' => 2048,
            ],
            [
                'name' => 'Senior Citizen ID',
                'code' => 'senior_citizen_id',
                'description' => 'Office of Senior Citizen Affairs (OSCA) ID',
                'category' => 'identification',
                'is_required' => false,
                'sort_order' => 6,
                'accepted_formats' => ['jpg', 'jpeg', 'png', 'pdf'],
                'max_file_size' => 2048,
            ],
            [
                'name' => 'PWD ID',
                'code' => 'pwd_id',
                'description' => 'Persons with Disability Identification Card',
                'category' => 'identification',
                'is_required' => false,
                'sort_order' => 7,
                'accepted_formats' => ['jpg', 'jpeg', 'png', 'pdf'],
                'max_file_size' => 2048,
            ],

            // PROOF OF RESIDENCY
            [
                'name' => 'Proof of Residency',
                'code' => 'proof_of_residency',
                'description' => 'Utility bills (electricity, water, internet, landline), Credit card statement, Bank statement (must show name and address)',
                'category' => 'residency_proof',
                'is_required' => true,
                'sort_order' => 8,
                'accepted_formats' => ['jpg', 'jpeg', 'png', 'pdf'],
                'max_file_size' => 2048,
            ],
            [
                'name' => 'Lease/Rental Contract',
                'code' => 'lease_contract',
                'description' => 'Notarized lease or rental agreement',
                'category' => 'residency_proof',
                'is_required' => false,
                'sort_order' => 9,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 5120,
            ],
            [
                'name' => 'Barangay Certificate of Residency',
                'code' => 'barangay_residency_cert',
                'description' => 'Certificate issued by the barangay confirming residency',
                'category' => 'residency_proof',
                'is_required' => false,
                'sort_order' => 10,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 2048,
            ],
            [
                'name' => 'Tax Declaration',
                'code' => 'tax_declaration',
                'description' => 'Real Property Tax Declaration',
                'category' => 'residency_proof',
                'is_required' => false,
                'sort_order' => 11,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 5120,
            ],

            // FINANCIAL DOCUMENTS
            [
                'name' => 'Proof of Income',
                'code' => 'proof_of_income',
                'description' => 'Certificate of Employment with Compensation, Latest payslip, ITR, Business registration documents',
                'category' => 'financial',
                'is_required' => true,
                'sort_order' => 12,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 5120,
            ],
            [
                'name' => 'Certificate of Indigency',
                'code' => 'certificate_indigency',
                'description' => 'Certificate declaring low-income status',
                'category' => 'financial',
                'is_required' => false,
                'sort_order' => 13,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 2048,
            ],
            [
                'name' => 'ITR (Income Tax Return)',
                'code' => 'itr',
                'description' => 'Latest Income Tax Return',
                'category' => 'financial',
                'is_required' => false,
                'sort_order' => 14,
                'accepted_formats' => ['pdf'],
                'max_file_size' => 5120,
            ],
            [
                'name' => 'Bank Statement',
                'code' => 'bank_statement',
                'description' => 'Latest 3 months bank statement',
                'category' => 'financial',
                'is_required' => false,
                'sort_order' => 15,
                'accepted_formats' => ['pdf'],
                'max_file_size' => 5120,
            ],

            // EDUCATIONAL DOCUMENTS
            [
                'name' => 'Birth Certificate',
                'code' => 'birth_certificate',
                'description' => 'PSA-authenticated Birth Certificate',
                'category' => 'educational',
                'is_required' => false,
                'sort_order' => 16,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 2048,
            ],
            [
                'name' => 'Marriage Certificate',
                'code' => 'marriage_certificate',
                'description' => 'PSA-authenticated Marriage Certificate',
                'category' => 'educational',
                'is_required' => false,
                'sort_order' => 17,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 2048,
            ],
            [
                'name' => 'School ID',
                'code' => 'school_id',
                'description' => 'Valid School Identification Card',
                'category' => 'educational',
                'is_required' => false,
                'sort_order' => 18,
                'accepted_formats' => ['jpg', 'jpeg', 'png'],
                'max_file_size' => 2048,
            ],
            [
                'name' => 'Transcript of Records',
                'code' => 'transcript_records',
                'description' => 'Official Transcript of Records',
                'category' => 'educational',
                'is_required' => false,
                'sort_order' => 19,
                'accepted_formats' => ['pdf'],
                'max_file_size' => 5120,
            ],
            [
                'name' => 'Diploma',
                'code' => 'diploma',
                'description' => 'Graduation Diploma',
                'category' => 'educational',
                'is_required' => false,
                'sort_order' => 20,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 5120,
            ],

            // EMPLOYMENT DOCUMENTS
            [
                'name' => 'Certificate of Employment',
                'code' => 'certificate_employment',
                'description' => 'Certificate from current employer',
                'category' => 'employment',
                'is_required' => false,
                'sort_order' => 21,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 2048,
            ],
            [
                'name' => 'Pay Slip',
                'code' => 'payslip',
                'description' => 'Latest 3 months payslip',
                'category' => 'employment',
                'is_required' => false,
                'sort_order' => 22,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 5120,
            ],
            [
                'name' => 'Contract of Employment',
                'code' => 'employment_contract',
                'description' => 'Employment contract',
                'category' => 'employment',
                'is_required' => false,
                'sort_order' => 23,
                'accepted_formats' => ['pdf'],
                'max_file_size' => 5120,
            ],

            // BUSINESS DOCUMENTS
            [
                'name' => 'Business Permit',
                'code' => 'business_permit',
                'description' => 'Mayor\'s Permit/Business Permit',
                'category' => 'business',
                'is_required' => false,
                'sort_order' => 24,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 5120,
            ],
            [
                'name' => 'DTI/SEC Registration',
                'code' => 'dti_sec_registration',
                'description' => 'DTI Business Name Registration or SEC Certificate',
                'category' => 'business',
                'is_required' => false,
                'sort_order' => 25,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 5120,
            ],
            [
                'name' => 'Business Plan',
                'code' => 'business_plan',
                'description' => 'Detailed business plan',
                'category' => 'business',
                'is_required' => false,
                'sort_order' => 26,
                'accepted_formats' => ['pdf', 'doc', 'docx'],
                'max_file_size' => 10240,
            ],

            // LEGAL DOCUMENTS
            [
                'name' => 'Police Clearance',
                'code' => 'police_clearance',
                'description' => 'NBI or Police Clearance',
                'category' => 'legal',
                'is_required' => false,
                'sort_order' => 27,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 2048,
            ],
            [
                'name' => 'Barangay Clearance',
                'code' => 'barangay_clearance',
                'description' => 'Barangay Clearance Certificate',
                'category' => 'legal',
                'is_required' => false,
                'sort_order' => 28,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 2048,
            ],
            [
                'name' => 'Court Clearance',
                'code' => 'court_clearance',
                'description' => 'Court Clearance Certificate',
                'category' => 'legal',
                'is_required' => false,
                'sort_order' => 29,
                'accepted_formats' => ['pdf'],
                'max_file_size' => 2048,
            ],

            // MEDICAL DOCUMENTS
            [
                'name' => 'Medical Certificate',
                'code' => 'medical_certificate',
                'description' => 'Medical certificate from licensed physician',
                'category' => 'medical',
                'is_required' => false,
                'sort_order' => 30,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 2048,
            ],
            [
                'name' => 'Laboratory Results',
                'code' => 'lab_results',
                'description' => 'Medical laboratory test results',
                'category' => 'medical',
                'is_required' => false,
                'sort_order' => 31,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 5120,
            ],

            // PHOTOS
            [
                'name' => '2x2 ID Picture',
                'code' => 'photo_2x2',
                'description' => 'Recent 2x2 colored ID picture with white background',
                'category' => 'other',
                'is_required' => false,
                'sort_order' => 32,
                'accepted_formats' => ['jpg', 'jpeg', 'png'],
                'max_file_size' => 1024,
            ],
            [
                'name' => '1x1 ID Picture',
                'code' => 'photo_1x1',
                'description' => 'Recent 1x1 colored ID picture with white background',
                'category' => 'other',
                'is_required' => false,
                'sort_order' => 33,
                'accepted_formats' => ['jpg', 'jpeg', 'png'],
                'max_file_size' => 1024,
            ],

            // OTHER DOCUMENTS
            [
                'name' => 'Authorization Letter',
                'code' => 'authorization_letter',
                'description' => 'Notarized authorization letter if processing for someone else',
                'category' => 'other',
                'is_required' => false,
                'sort_order' => 34,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 2048,
            ],
            [
                'name' => 'Proof of Relationship',
                'code' => 'proof_relationship',
                'description' => 'Birth certificate, marriage certificate, or affidavit of relationship',
                'category' => 'other',
                'is_required' => false,
                'sort_order' => 35,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 2048,
            ],
            [
                'name' => 'Affidavit',
                'code' => 'affidavit',
                'description' => 'Notarized affidavit for various purposes',
                'category' => 'other',
                'is_required' => false,
                'sort_order' => 36,
                'accepted_formats' => ['pdf', 'jpg', 'jpeg'],
                'max_file_size' => 2048,
            ],
        ];

        foreach ($documentTypes as $type) {
            DocumentType::create($type);
        }

        $this->command->info('Document types seeded successfully!');
    }
}