<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class FeeTypesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();
        
        $feeTypes = [
            // =========== TAXATION & FEES (Category ID: 13) ===========
            [
                'code' => 'TAX-RP-001',
                'document_category_id' => 13,
                'name' => 'Real Property Tax',
                'short_name' => 'RPT',
                'base_amount' => 500.00,
                'amount_type' => 'fixed',
                'computation_formula' => null,
                'unit' => 'per property',
                'description' => 'Annual tax on real properties within the barangay',
                'has_senior_discount' => 1,
                'senior_discount_percentage' => 20.00,
                'has_pwd_discount' => 1,
                'pwd_discount_percentage' => 20.00,
                'has_solo_parent_discount' => 1,
                'solo_parent_discount_percentage' => 15.00,
                'has_indigent_discount' => 1,
                'indigent_discount_percentage' => 30.00,
                'has_surcharge' => 1,
                'surcharge_percentage' => 2.00,
                'surcharge_fixed' => 50.00,
                'has_penalty' => 1,
                'penalty_percentage' => 2.00,
                'penalty_fixed' => 25.00,
                'frequency' => 'annual',
                'validity_days' => 365,
                'applicable_to' => 'property_owners',
                'applicable_puroks' => '[]',
                'requirements' => '["Tax Declaration","Latest Receipt"]',
                'effective_date' => '2026-01-01',
                'expiry_date' => null,
                'is_active' => 1,
                'is_mandatory' => 1,
                'auto_generate' => 1,
                'due_day' => 31,
                'sort_order' => 1,
                'notes' => 'Due every January 31st',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'TAX-BUS-002',
                'document_category_id' => 13,
                'name' => 'Business Permit Fee',
                'short_name' => 'BP Fee',
                'base_amount' => 1000.00,
                'amount_type' => 'fixed', // Changed from computed to fixed
                'computation_formula' => null, // Set to null
                'unit' => 'per business',
                'description' => 'Annual business permit fee',
                'has_senior_discount' => 0,
                'senior_discount_percentage' => null,
                'has_pwd_discount' => 0,
                'pwd_discount_percentage' => null,
                'has_solo_parent_discount' => 0,
                'solo_parent_discount_percentage' => null,
                'has_indigent_discount' => 0,
                'indigent_discount_percentage' => null,
                'has_surcharge' => 1,
                'surcharge_percentage' => 3.00,
                'surcharge_fixed' => 100.00,
                'has_penalty' => 1,
                'penalty_percentage' => 5.00,
                'penalty_fixed' => 200.00,
                'frequency' => 'annual',
                'validity_days' => 365,
                'applicable_to' => 'business_owners',
                'applicable_puroks' => '[]',
                'requirements' => '["DTI\/SEC Registration","Mayor\'s Permit"]',
                'effective_date' => '2026-01-01',
                'expiry_date' => null,
                'is_active' => 1,
                'is_mandatory' => 1,
                'auto_generate' => 1,
                'due_day' => 20,
                'sort_order' => 2,
                'notes' => 'Renewable every year',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'TAX-MK-003',
                'document_category_id' => 13,
                'name' => 'Market Stall Fee',
                'short_name' => 'Market Fee',
                'base_amount' => 300.00,
                'amount_type' => 'fixed',
                'computation_formula' => null,
                'unit' => 'per month',
                'description' => 'Monthly rental fee for market stall occupants',
                'has_senior_discount' => 1,
                'senior_discount_percentage' => 10.00,
                'has_pwd_discount' => 1,
                'pwd_discount_percentage' => 10.00,
                'has_solo_parent_discount' => 1,
                'solo_parent_discount_percentage' => 10.00,
                'has_indigent_discount' => 1,
                'indigent_discount_percentage' => 15.00,
                'has_surcharge' => 1,
                'surcharge_percentage' => 2.00,
                'surcharge_fixed' => 20.00,
                'has_penalty' => 1,
                'penalty_percentage' => 3.00,
                'penalty_fixed' => 30.00,
                'frequency' => 'monthly',
                'validity_days' => 30,
                'applicable_to' => 'market_vendors',
                'applicable_puroks' => '[]',
                'requirements' => '["Market Stall Contract"]',
                'effective_date' => '2026-01-01',
                'expiry_date' => null,
                'is_active' => 1,
                'is_mandatory' => 1,
                'auto_generate' => 1,
                'due_day' => 5,
                'sort_order' => 3,
                'notes' => 'Due every 5th of the month',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // =========== LICENSES & PERMITS (Category ID: 8) ===========
            [
                'code' => 'LP-CN-004',
                'document_category_id' => 8,
                'name' => 'Construction Permit Fee',
                'short_name' => 'Building Permit',
                'base_amount' => 1500.00,
                'amount_type' => 'fixed', // Changed from computed to fixed
                'computation_formula' => null, // Set to null
                'unit' => 'per sqm',
                'description' => 'Fee for construction and renovation permits',
                'has_senior_discount' => 0,
                'senior_discount_percentage' => null,
                'has_pwd_discount' => 0,
                'pwd_discount_percentage' => null,
                'has_solo_parent_discount' => 0,
                'solo_parent_discount_percentage' => null,
                'has_indigent_discount' => 0,
                'indigent_discount_percentage' => null,
                'has_surcharge' => 1,
                'surcharge_percentage' => 5.00,
                'surcharge_fixed' => 200.00,
                'has_penalty' => 1,
                'penalty_percentage' => 10.00,
                'penalty_fixed' => 500.00,
                'frequency' => 'one_time',
                'validity_days' => 180,
                'applicable_to' => 'property_owners',
                'applicable_puroks' => '[]',
                'requirements' => '["Building Plans","Barangay Clearance"]',
                'effective_date' => '2026-01-01',
                'expiry_date' => null,
                'is_active' => 1,
                'is_mandatory' => 1,
                'auto_generate' => 0,
                'due_day' => null,
                'sort_order' => 4,
                'notes' => 'Valid for 6 months from issuance',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'LP-SG-005',
                'document_category_id' => 8,
                'name' => 'Sidewalk/Special Event Permit',
                'short_name' => 'Event Permit',
                'base_amount' => 500.00,
                'amount_type' => 'fixed',
                'computation_formula' => null,
                'unit' => 'per event',
                'description' => 'Fee for special events and sidewalk usage',
                'has_senior_discount' => 0,
                'senior_discount_percentage' => null,
                'has_pwd_discount' => 0,
                'pwd_discount_percentage' => null,
                'has_solo_parent_discount' => 0,
                'solo_parent_discount_percentage' => null,
                'has_indigent_discount' => 0,
                'indigent_discount_percentage' => null,
                'has_surcharge' => 0,
                'surcharge_percentage' => null,
                'surcharge_fixed' => null,
                'has_penalty' => 0,
                'penalty_percentage' => null,
                'penalty_fixed' => null,
                'frequency' => 'one_time',
                'validity_days' => 7,
                'applicable_to' => 'all_residents',
                'applicable_puroks' => '[]',
                'requirements' => '["Event Details","Barangay Clearance"]',
                'effective_date' => '2026-01-01',
                'expiry_date' => null,
                'is_active' => 1,
                'is_mandatory' => 0,
                'auto_generate' => 0,
                'due_day' => null,
                'sort_order' => 5,
                'notes' => 'Apply at least 3 days before event',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // =========== BUSINESS (Category ID: 6) ===========
            [
                'code' => 'BUS-CL-006',
                'document_category_id' => 6,
                'name' => 'Barangay Clearance for Business',
                'short_name' => 'Business Clearance',
                'base_amount' => 200.00,
                'amount_type' => 'fixed',
                'computation_formula' => null,
                'unit' => 'per application',
                'description' => 'Clearance for new business registration',
                'has_senior_discount' => 1,
                'senior_discount_percentage' => 20.00,
                'has_pwd_discount' => 1,
                'pwd_discount_percentage' => 20.00,
                'has_solo_parent_discount' => 1,
                'solo_parent_discount_percentage' => 15.00,
                'has_indigent_discount' => 1,
                'indigent_discount_percentage' => 30.00,
                'has_surcharge' => 0,
                'surcharge_percentage' => null,
                'surcharge_fixed' => null,
                'has_penalty' => 0,
                'penalty_percentage' => null,
                'penalty_fixed' => null,
                'frequency' => 'one_time',
                'validity_days' => 365,
                'applicable_to' => 'business_owners',
                'applicable_puroks' => '[]',
                'requirements' => '["Valid ID","Business Plan"]',
                'effective_date' => '2026-01-01',
                'expiry_date' => null,
                'is_active' => 1,
                'is_mandatory' => 1,
                'auto_generate' => 0,
                'due_day' => null,
                'sort_order' => 6,
                'notes' => 'Required for Mayor\'s Permit application',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'BUS-RN-007',
                'document_category_id' => 6,
                'name' => 'Business Permit Renewal',
                'short_name' => 'Business Renewal',
                'base_amount' => 150.00,
                'amount_type' => 'fixed',
                'computation_formula' => null,
                'unit' => 'per renewal',
                'description' => 'Fee for annual business permit renewal',
                'has_senior_discount' => 1,
                'senior_discount_percentage' => 15.00,
                'has_pwd_discount' => 1,
                'pwd_discount_percentage' => 15.00,
                'has_solo_parent_discount' => 1,
                'solo_parent_discount_percentage' => 10.00,
                'has_indigent_discount' => 1,
                'indigent_discount_percentage' => 25.00,
                'has_surcharge' => 1,
                'surcharge_percentage' => 2.00,
                'surcharge_fixed' => 50.00,
                'has_penalty' => 1,
                'penalty_percentage' => 5.00,
                'penalty_fixed' => 100.00,
                'frequency' => 'annual',
                'validity_days' => 365,
                'applicable_to' => 'business_owners',
                'applicable_puroks' => '[]',
                'requirements' => '["Previous Permit","Updated Business Info"]',
                'effective_date' => '2026-01-01',
                'expiry_date' => null,
                'is_active' => 1,
                'is_mandatory' => 1,
                'auto_generate' => 1,
                'due_day' => 20,
                'sort_order' => 7,
                'notes' => 'Due every January 20th',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // =========== COMMUNITY CERTIFICATES (Category ID: 7) ===========
            [
                'code' => 'CC-RS-008',
                'document_category_id' => 7,
                'name' => 'Community Tax Certificate (Cedula)',
                'short_name' => 'Cedula',
                'base_amount' => 50.00,
                'amount_type' => 'per_unit',
                'computation_formula' => null,
                'unit' => 'per person',
                'description' => 'Community Tax Certificate for residents',
                'has_senior_discount' => 1,
                'senior_discount_percentage' => 100.00,
                'has_pwd_discount' => 1,
                'pwd_discount_percentage' => 100.00,
                'has_solo_parent_discount' => 1,
                'solo_parent_discount_percentage' => 50.00,
                'has_indigent_discount' => 1,
                'indigent_discount_percentage' => 100.00,
                'has_surcharge' => 1,
                'surcharge_percentage' => 2.00,
                'surcharge_fixed' => 10.00,
                'has_penalty' => 1,
                'penalty_percentage' => 5.00,
                'penalty_fixed' => 20.00,
                'frequency' => 'annual',
                'validity_days' => 365,
                'applicable_to' => 'all_residents',
                'applicable_puroks' => '[]',
                'requirements' => '["Valid ID","Proof of Residence"]',
                'effective_date' => '2026-01-01',
                'expiry_date' => null,
                'is_active' => 1,
                'is_mandatory' => 1,
                'auto_generate' => 0,
                'due_day' => 31,
                'sort_order' => 8,
                'notes' => 'Free for seniors, PWDs, and indigents',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'CC-ID-009',
                'document_category_id' => 7,
                'name' => 'Indigency Certificate',
                'short_name' => 'Indigency Cert',
                'base_amount' => 20.00,
                'amount_type' => 'fixed',
                'computation_formula' => null,
                'unit' => 'per certificate',
                'description' => 'Certificate for indigent individuals',
                'has_senior_discount' => 1,
                'senior_discount_percentage' => 100.00,
                'has_pwd_discount' => 1,
                'pwd_discount_percentage' => 100.00,
                'has_solo_parent_discount' => 1,
                'solo_parent_discount_percentage' => 100.00,
                'has_indigent_discount' => 1,
                'indigent_discount_percentage' => 100.00,
                'has_surcharge' => 0,
                'surcharge_percentage' => null,
                'surcharge_fixed' => null,
                'has_penalty' => 0,
                'penalty_percentage' => null,
                'penalty_fixed' => null,
                'frequency' => 'one_time',
                'validity_days' => 90,
                'applicable_to' => 'all_residents',
                'applicable_puroks' => '[]',
                'requirements' => '["Proof of Income","Household Survey"]',
                'effective_date' => '2026-01-01',
                'expiry_date' => null,
                'is_active' => 1,
                'is_mandatory' => 0,
                'auto_generate' => 0,
                'due_day' => null,
                'sort_order' => 9,
                'notes' => 'Free for qualified individuals',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // =========== IDENTIFICATION (Category ID: 1) ===========
            [
                'code' => 'ID-BC-010',
                'document_category_id' => 1,
                'name' => 'Barangay ID Card',
                'short_name' => 'Barangay ID',
                'base_amount' => 100.00,
                'amount_type' => 'fixed',
                'computation_formula' => null,
                'unit' => 'per ID',
                'description' => 'Barangay Identification Card',
                'has_senior_discount' => 1,
                'senior_discount_percentage' => 100.00,
                'has_pwd_discount' => 1,
                'pwd_discount_percentage' => 100.00,
                'has_solo_parent_discount' => 1,
                'solo_parent_discount_percentage' => 50.00,
                'has_indigent_discount' => 1,
                'indigent_discount_percentage' => 100.00,
                'has_surcharge' => 0,
                'surcharge_percentage' => null,
                'surcharge_fixed' => null,
                'has_penalty' => 0,
                'penalty_percentage' => null,
                'penalty_fixed' => null,
                'frequency' => 'one_time',
                'validity_days' => 1095,
                'applicable_to' => 'all_residents',
                'applicable_puroks' => '[]',
                'requirements' => '["2x2 Photo","Proof of Residence"]',
                'effective_date' => '2026-01-01',
                'expiry_date' => null,
                'is_active' => 1,
                'is_mandatory' => 0,
                'auto_generate' => 0,
                'due_day' => null,
                'sort_order' => 10,
                'notes' => 'Valid for 3 years',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // =========== HEALTH (Category ID: 4) ===========
            [
                'code' => 'HL-HC-011',
                'document_category_id' => 4,
                'name' => 'Health Certificate',
                'short_name' => 'Health Cert',
                'base_amount' => 100.00,
                'amount_type' => 'fixed',
                'computation_formula' => null,
                'unit' => 'per certificate',
                'description' => 'Medical certificate for employment/food handling',
                'has_senior_discount' => 1,
                'senior_discount_percentage' => 50.00,
                'has_pwd_discount' => 1,
                'pwd_discount_percentage' => 50.00,
                'has_solo_parent_discount' => 1,
                'solo_parent_discount_percentage' => 30.00,
                'has_indigent_discount' => 1,
                'indigent_discount_percentage' => 100.00,
                'has_surcharge' => 0,
                'surcharge_percentage' => null,
                'surcharge_fixed' => null,
                'has_penalty' => 0,
                'penalty_percentage' => null,
                'penalty_fixed' => null,
                'frequency' => 'one_time',
                'validity_days' => 180,
                'applicable_to' => 'all_residents',
                'applicable_puroks' => '[]',
                'requirements' => '["Medical Exam","Lab Results"]',
                'effective_date' => '2026-01-01',
                'expiry_date' => null,
                'is_active' => 1,
                'is_mandatory' => 0,
                'auto_generate' => 0,
                'due_day' => null,
                'sort_order' => 11,
                'notes' => 'Valid for 6 months',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // =========== PROPERTY & REAL ESTATE (Category ID: 10) ===========
            [
                'code' => 'PR-CL-012',
                'document_category_id' => 10,
                'name' => 'Property Transfer Clearance',
                'short_name' => 'Property Transfer',
                'base_amount' => 300.00,
                'amount_type' => 'fixed',
                'computation_formula' => null,
                'unit' => 'per transfer',
                'description' => 'Clearance for property ownership transfer',
                'has_senior_discount' => 1,
                'senior_discount_percentage' => 20.00,
                'has_pwd_discount' => 1,
                'pwd_discount_percentage' => 20.00,
                'has_solo_parent_discount' => 1,
                'solo_parent_discount_percentage' => 15.00,
                'has_indigent_discount' => 1,
                'indigent_discount_percentage' => 30.00,
                'has_surcharge' => 0,
                'surcharge_percentage' => null,
                'surcharge_fixed' => null,
                'has_penalty' => 0,
                'penalty_percentage' => null,
                'penalty_fixed' => null,
                'frequency' => 'one_time',
                'validity_days' => 30,
                'applicable_to' => 'property_owners',
                'applicable_puroks' => '[]',
                'requirements' => '["Deed of Sale","Tax Declaration"]',
                'effective_date' => '2026-01-01',
                'expiry_date' => null,
                'is_active' => 1,
                'is_mandatory' => 1,
                'auto_generate' => 0,
                'due_day' => null,
                'sort_order' => 12,
                'notes' => 'Required for Registry of Deeds',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // =========== TRANSPORTATION & TRAFFIC (Category ID: 15) ===========
            [
                'code' => 'TT-TR-013',
                'document_category_id' => 15,
                'name' => 'Tricycle Franchise Fee',
                'short_name' => 'Tricycle Fee',
                'base_amount' => 1200.00,
                'amount_type' => 'fixed',
                'computation_formula' => null,
                'unit' => 'per year',
                'description' => 'Annual franchise fee for tricycle operators',
                'has_senior_discount' => 1,
                'senior_discount_percentage' => 20.00,
                'has_pwd_discount' => 1,
                'pwd_discount_percentage' => 20.00,
                'has_solo_parent_discount' => 1,
                'solo_parent_discount_percentage' => 15.00,
                'has_indigent_discount' => 1,
                'indigent_discount_percentage' => 30.00,
                'has_surcharge' => 1,
                'surcharge_percentage' => 3.00,
                'surcharge_fixed' => 100.00,
                'has_penalty' => 1,
                'penalty_percentage' => 5.00,
                'penalty_fixed' => 200.00,
                'frequency' => 'annual',
                'validity_days' => 365,
                'applicable_to' => 'tricycle_operators',
                'applicable_puroks' => '[]',
                'requirements' => '["Driver\'s License","OR\/CR"]',
                'effective_date' => '2026-01-01',
                'expiry_date' => null,
                'is_active' => 1,
                'is_mandatory' => 1,
                'auto_generate' => 1,
                'due_day' => 15,
                'sort_order' => 13,
                'notes' => 'Due every January 15th',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // =========== COMMUNITY SERVICES (Category ID: 11) ===========
            [
                'code' => 'CS-BC-014',
                'document_category_id' => 11,
                'name' => 'Barangay Clearance',
                'short_name' => 'Clearance',
                'base_amount' => 50.00,
                'amount_type' => 'fixed',
                'computation_formula' => null,
                'unit' => 'per clearance',
                'description' => 'General barangay clearance for various purposes',
                'has_senior_discount' => 1,
                'senior_discount_percentage' => 50.00,
                'has_pwd_discount' => 1,
                'pwd_discount_percentage' => 50.00,
                'has_solo_parent_discount' => 1,
                'solo_parent_discount_percentage' => 30.00,
                'has_indigent_discount' => 1,
                'indigent_discount_percentage' => 100.00,
                'has_surcharge' => 0,
                'surcharge_percentage' => null,
                'surcharge_fixed' => null,
                'has_penalty' => 0,
                'penalty_percentage' => null,
                'penalty_fixed' => null,
                'frequency' => 'one_time',
                'validity_days' => 30,
                'applicable_to' => 'all_residents',
                'applicable_puroks' => '[]',
                'requirements' => '["Valid ID","Purpose Letter"]',
                'effective_date' => '2026-01-01',
                'expiry_date' => null,
                'is_active' => 1,
                'is_mandatory' => 0,
                'auto_generate' => 0,
                'due_day' => null,
                'sort_order' => 14,
                'notes' => 'For employment, travel, etc.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
        
        // Insert fee types
        try {
            DB::table('fee_types')->insert($feeTypes);
            $this->command->info('Fee types seeded successfully!');
        } catch (\Exception $e) {
            $this->command->error('Error seeding fee types: ' . $e->getMessage());
        }
    }
}