{{ $barangay_name }}
{{ str_repeat('=', strlen($barangay_name)) }}

{{ $title }}
{{ str_repeat('-', strlen($title)) }}

Generated: {{ $generated_at->format('F j, Y g:i A') }}
Generated by: {{ $generated_by }}
Version: {{ $version }}
Type: {{ ucfirst($type) }} Guide

{{ str_repeat('=', 80) }}

@if($type === 'section' && isset($section))
{{ $section['title'] }}
{{ str_repeat('-', strlen($section['title'])) }}

{{ $section['description'] }}

{{ strip_tags($section['content']) }}
@else
@foreach($sections as $index => $section)
{{ sprintf('%02d', $index + 1) }}. {{ $section['title'] }}
{{ str_repeat('-', strlen($section['title']) + 5) }}

{{ $section['description'] }}

{{ strip_tags($section['content']) }}

@endforeach
@endif

@if(!empty($statistics))
SYSTEM STATISTICS
{{ str_repeat('=', 16) }}

@foreach($statistics as $key => $value)
{{ str_pad(ucwords(str_replace('_', ' ', $key)), 30) }} : 
@if(is_numeric($value))
@if(str_contains($key, 'amount') || str_contains($key, 'collection') || str_contains($key, 'payment'))
₱ {{ number_format($value, 2) }}
@else
{{ number_format($value) }}
@endif
@else
{{ $value }}
@endif

@endforeach
@endif

@if(!empty($quick_tips))
QUICK TIPS
{{ str_repeat('=', 10) }}

@foreach($quick_tips as $index => $tip)
{{ $index + 1 }}. {{ $tip }}
@endforeach

@endif

@if(!empty($shortcuts))
KEYBOARD SHORTCUTS
{{ str_repeat('=', 18) }}

@foreach($shortcuts as $shortcut)
{{ str_pad($shortcut['description'], 40) }} [{{ $shortcut['key'] }}]
@endforeach

@endif

@if(!empty($recent_updates))
VERSION HISTORY
{{ str_repeat('=', 14) }}

@foreach($recent_updates as $update)
Version {{ $update['version'] }} ({{ $update['date'] }})
{{ str_repeat('-', strlen($update['version']) + strlen($update['date']) + 10) }}
@foreach($update['changes'] as $change)
  • {{ $change }}
@endforeach

@endforeach
@endif

{{ str_repeat('=', 80) }}

© {{ date('Y') }} {{ $barangay_name }}. All rights reserved.
This document is confidential and for internal use only.
Generated on {{ $generated_at->format('F j, Y \a\t g:i A') }}

Document ID: {{ strtoupper(uniqid()) }}