<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ResidentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('Seeding residents...');
        
        $users = DB::table('users')->get()->keyBy('username');
        $puroks = DB::table('puroks')->get()->keyBy('slug');
        
        $residents = $this->getResidentsData($users, $puroks);

        foreach ($residents as $resident) {
            DB::table('residents')->updateOrInsert(
                ['resident_id' => $resident['resident_id']],
                array_merge($resident, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
        
        $this->command->info('✅ Seeded ' . count($residents) . ' residents');
    }
    
    /**
     * Get residents data
     */
    private function getResidentsData($users, $puroks): array
    {
        return [
            [
                'first_name' => 'Juan',
                'last_name' => 'Dela Cruz',
                'middle_name' => 'Santos',
                'birth_date' => '1985-03-15',
                'age' => 39,
                'gender' => 'male',
                'civil_status' => 'Married',
                'contact_number' => '09171234567',
                'email' => 'juan.delacruz@email.com',
                'address' => 'Purok 1, Barangay Sample',
                'purok_id' => $puroks['purok-1']->id ?? null,
                'occupation' => 'Farmer',
                'employment_status' => 'Self-employed',
                'educational_attainment' => 'College Graduate',
                'religion' => 'Roman Catholic',
                'is_voter' => 1,
                'place_of_birth' => 'Manila',
                'status' => 'active',
                'resident_id' => 'RES-2024-001',
                'user_id' => $users['admin']->id ?? null,
            ],
            [
                'first_name' => 'Maria',
                'last_name' => 'Santos',
                'middle_name' => 'Cruz',
                'birth_date' => '1990-07-22',
                'age' => 34,
                'gender' => 'female',
                'civil_status' => 'Married',
                'contact_number' => '09172345678',
                'email' => 'maria.santos@email.com',
                'address' => 'Purok 1, Barangay Sample',
                'purok_id' => $puroks['purok-1']->id ?? null,
                'occupation' => 'Teacher',
                'employment_status' => 'Employed',
                'educational_attainment' => 'Master\'s Degree',
                'religion' => 'Roman Catholic',
                'is_voter' => 1,
                'place_of_birth' => 'Quezon City',
                'status' => 'active',
                'resident_id' => 'RES-2024-002',
                'user_id' => $users['captain']->id ?? null,
            ],
            [
                'first_name' => 'Jose',
                'last_name' => 'Reyes',
                'middle_name' => 'Gonzales',
                'birth_date' => '1988-05-10',
                'age' => 36,
                'gender' => 'male',
                'civil_status' => 'Married',
                'contact_number' => '09173456789',
                'email' => 'jose.reyes@barangay.gov.ph',
                'address' => 'Purok 2, Barangay Sample',
                'purok_id' => $puroks['purok-2']->id ?? null,
                'occupation' => 'Government Employee',
                'employment_status' => 'Employed',
                'educational_attainment' => 'College Graduate',
                'religion' => 'Roman Catholic',
                'is_voter' => 1,
                'place_of_birth' => 'Bulacan',
                'status' => 'active',
                'resident_id' => 'RES-2024-003',
                'user_id' => $users['secretary']->id ?? null,
            ],
            [
                'first_name' => 'Teresita',
                'last_name' => 'Garcia',
                'middle_name' => 'Lopez',
                'birth_date' => '1975-12-15',
                'age' => 49,
                'gender' => 'female',
                'civil_status' => 'Married',
                'contact_number' => '09174567890',
                'email' => 'teresita.garcia@barangay.gov.ph',
                'address' => 'Purok 3, Barangay Sample',
                'purok_id' => $puroks['purok-3']->id ?? null,
                'occupation' => 'Accountant',
                'employment_status' => 'Employed',
                'educational_attainment' => 'College Graduate',
                'religion' => 'Roman Catholic',
                'is_voter' => 1,
                'place_of_birth' => 'Manila',
                'status' => 'active',
                'resident_id' => 'RES-2024-004',
                'user_id' => $users['treasurer']->id ?? null,
            ],
            [
                'first_name' => 'Pedro',
                'last_name' => 'Fernandez',
                'middle_name' => 'Gonzales',
                'birth_date' => '1995-11-05',
                'age' => 29,
                'gender' => 'male',
                'civil_status' => 'Single',
                'contact_number' => '09175678901',
                'email' => 'pedro.fernandez@email.com',
                'address' => 'Purok 2, Barangay Sample',
                'purok_id' => $puroks['purok-2']->id ?? null,
                'occupation' => 'Software Developer',
                'employment_status' => 'Employed',
                'educational_attainment' => 'College Graduate',
                'religion' => 'Iglesia Ni Cristo',
                'is_voter' => 1,
                'place_of_birth' => 'Cebu City',
                'status' => 'active',
                'resident_id' => 'RES-2024-005',
                'user_id' => $users['resident1']->id ?? null,
            ],
            [
                'first_name' => 'Ana',
                'last_name' => 'Reyes',
                'middle_name' => 'Lopez',
                'birth_date' => '1988-02-18',
                'age' => 36,
                'gender' => 'female',
                'civil_status' => 'Married',
                'contact_number' => '09176789012',
                'email' => 'ana.reyes@email.com',
                'address' => 'Purok 3, Barangay Sample',
                'purok_id' => $puroks['purok-3']->id ?? null,
                'occupation' => 'Business Owner',
                'employment_status' => 'Self-employed',
                'educational_attainment' => 'College Graduate',
                'religion' => 'Roman Catholic',
                'is_voter' => 1,
                'place_of_birth' => 'Davao City',
                'status' => 'active',
                'resident_id' => 'RES-2024-006',
                'user_id' => $users['resident2']->id ?? null,
            ],
            [
                'first_name' => 'Carlos',
                'last_name' => 'Mendoza',
                'middle_name' => 'Villanueva',
                'birth_date' => '1982-09-30',
                'age' => 42,
                'gender' => 'male',
                'civil_status' => 'Married',
                'contact_number' => '09177890123',
                'email' => 'carlos.mendoza@business.com',
                'address' => 'Purok 3, Barangay Sample',
                'purok_id' => $puroks['purok-3']->id ?? null,
                'occupation' => 'Store Owner',
                'employment_status' => 'Self-employed',
                'educational_attainment' => 'High School Graduate',
                'religion' => 'Roman Catholic',
                'is_voter' => 1,
                'place_of_birth' => 'Bulacan',
                'status' => 'active',
                'resident_id' => 'RES-2024-007',
                'user_id' => $users['business']->id ?? null,
            ],
            [
                'first_name' => 'Luz',
                'last_name' => 'Villanueva',
                'middle_name' => 'Ramirez',
                'birth_date' => '1960-05-12',
                'age' => 64,
                'gender' => 'female',
                'civil_status' => 'Widowed',
                'contact_number' => '09178901234',
                'email' => 'luz.villanueva@email.com',
                'address' => 'Purok 2, Barangay Sample',
                'purok_id' => $puroks['purok-2']->id ?? null,
                'occupation' => 'Retired',
                'employment_status' => 'Retired',
                'educational_attainment' => 'Elementary Graduate',
                'religion' => 'Roman Catholic',
                'is_voter' => 1,
                'place_of_birth' => 'Pampanga',
                'status' => 'active',
                'resident_id' => 'RES-2024-008',
                'user_id' => $users['viewer']->id ?? null,
            ],
            [
                'first_name' => 'Ramon',
                'last_name' => 'Aquino',
                'middle_name' => 'Dela Cruz',
                'birth_date' => '1992-08-25',
                'age' => 32,
                'gender' => 'male',
                'civil_status' => 'Single',
                'contact_number' => '09179012345',
                'email' => 'ramon.aquino@barangay.gov.ph',
                'address' => 'Purok 1, Barangay Sample',
                'purok_id' => $puroks['purok-1']->id ?? null,
                'occupation' => 'Staff',
                'employment_status' => 'Employed',
                'educational_attainment' => 'College Graduate',
                'religion' => 'Roman Catholic',
                'is_voter' => 1,
                'place_of_birth' => 'Manila',
                'status' => 'active',
                'resident_id' => 'RES-2024-009',
                'user_id' => $users['staff']->id ?? null,
            ],
            [
                'first_name' => 'Josefa',
                'last_name' => 'Llanes',
                'middle_name' => 'Escoda',
                'birth_date' => '1985-09-20',
                'age' => 39,
                'gender' => 'female',
                'civil_status' => 'Married',
                'contact_number' => '09170123456',
                'email' => 'josefa.llanes@barangay.gov.ph',
                'address' => 'Purok 4, Barangay Sample',
                'purok_id' => $puroks['purok-4']->id ?? null,
                'occupation' => 'Councilor',
                'employment_status' => 'Employed',
                'educational_attainment' => 'College Graduate',
                'religion' => 'Roman Catholic',
                'is_voter' => 1,
                'place_of_birth' => 'Manila',
                'status' => 'active',
                'resident_id' => 'RES-2024-010',
                'user_id' => $users['kagawad']->id ?? null,
            ],
            [
                'first_name' => 'Andres',
                'last_name' => 'Bonifacio',
                'middle_name' => 'Castro',
                'birth_date' => '1998-11-30',
                'age' => 26,
                'gender' => 'male',
                'civil_status' => 'Single',
                'contact_number' => '09171234568',
                'email' => 'andres.bonifacio@barangay.gov.ph',
                'address' => 'Purok 5, Barangay Sample',
                'purok_id' => $puroks['purok-5']->id ?? null,
                'occupation' => 'Student',
                'employment_status' => 'Student',
                'educational_attainment' => 'College Level',
                'religion' => 'Roman Catholic',
                'is_voter' => 1,
                'place_of_birth' => 'Tondo',
                'status' => 'active',
                'resident_id' => 'RES-2024-011',
                'user_id' => $users['skchairman']->id ?? null,
            ],
            [
                'first_name' => 'Gabriela',
                'last_name' => 'Silang',
                'middle_name' => 'Carino',
                'birth_date' => '1980-03-19',
                'age' => 44,
                'gender' => 'female',
                'civil_status' => 'Married',
                'contact_number' => '09172345679',
                'email' => 'gabriela.silang@barangay.gov.ph',
                'address' => 'Purok 6, Barangay Sample',
                'purok_id' => $puroks['purok-6']->id ?? null,
                'occupation' => 'Finance Officer',
                'employment_status' => 'Employed',
                'educational_attainment' => 'College Graduate',
                'religion' => 'Roman Catholic',
                'is_voter' => 1,
                'place_of_birth' => 'Ilocos',
                'status' => 'active',
                'resident_id' => 'RES-2024-012',
                'user_id' => $users['treasuryofficer']->id ?? null,
            ],
            [
                'first_name' => 'Melchora',
                'last_name' => 'Aquino',
                'middle_name' => 'De Jesus',
                'birth_date' => '1987-01-06',
                'age' => 37,
                'gender' => 'female',
                'civil_status' => 'Married',
                'contact_number' => '09173456780',
                'email' => 'melchora.aquino@barangay.gov.ph',
                'address' => 'Purok 7, Barangay Sample',
                'purok_id' => $puroks['purok-7']->id ?? null,
                'occupation' => 'Records Manager',
                'employment_status' => 'Employed',
                'educational_attainment' => 'College Graduate',
                'religion' => 'Roman Catholic',
                'is_voter' => 1,
                'place_of_birth' => 'Quezon City',
                'status' => 'active',
                'resident_id' => 'RES-2024-013',
                'user_id' => $users['recordclerk']->id ?? null,
            ],
            [
                'first_name' => 'Emilio',
                'last_name' => 'Aguinaldo',
                'middle_name' => 'Famy',
                'birth_date' => '1983-03-22',
                'age' => 41,
                'gender' => 'male',
                'civil_status' => 'Married',
                'contact_number' => '09174567891',
                'email' => 'emilio.aguinaldo@barangay.gov.ph',
                'address' => 'Purok 8, Barangay Sample',
                'purok_id' => $puroks['purok-8']->id ?? null,
                'occupation' => 'Clearance Officer',
                'employment_status' => 'Employed',
                'educational_attainment' => 'College Graduate',
                'religion' => 'Roman Catholic',
                'is_voter' => 1,
                'place_of_birth' => 'Cavite',
                'status' => 'active',
                'resident_id' => 'RES-2024-014',
                'user_id' => $users['clearanceofficer']->id ?? null,
            ],
        ];
    }
}