// Re-export all Lucide icons with better organization
export {
    // Navigation & Actions
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowDown,
    ChevronDown,
    ChevronUp,
    ChevronLeft,
    ChevronRight,
    Home,
    Settings,
    Menu,
    X,
    Check,
    Plus,
    Minus,
    Search,
    Filter,
    Upload,
    Download,
    Edit,
    Trash2,
    Eye,
    EyeOff,
    Lock,
    Unlock,
    Key,
    LogOut,
    User,
    Users,
    UserPlus,
    UserMinus,
    
    // Status & Alerts
    AlertCircle,
    AlertTriangle,
    AlertOctagon,
    CheckCircle,
    XCircle,
    Info,
    HelpCircle,
    Ban,
    Shield,
    ShieldAlert,
    ShieldOff,
    Bell,
    BellRing,
    BellOff,
    
    // Communication
    MessageSquare,
    MessageCircle,
    Mail,
    Phone,
    Send,
    Share2,
    ThumbsUp,
    ThumbsDown,
    Star,
    Heart,
    Flag,
    
    // Files & Documents
    File,
    FileText,
    FileImage,
    FileVideo,
    FileAudio,
    FileArchive,
    FileCode,
    FileSpreadsheet,
    Folder,
    FolderOpen,
    Clipboard,
    ClipboardCopy,
    ClipboardCheck,
    Save,
    
    // Time & Date
    Calendar,
    Clock,
    Timer,
    Watch,
    CalendarDays,
    CalendarRange,
    
    // Location
    MapPin,
    Map,
    Compass,
    Navigation,
    Globe,
    
    // Media
    Camera,
    Video,
    Mic,
    MicOff,
    Volume,
    Volume2,
    VolumeX,
    Headphones,
    Speaker,
    Music,
    Film,
    Tv,
    Radio,
    
    // Technology
    Smartphone,
    Laptop,
    Tablet,
    Monitor,
    Printer,
    Server,
    Database,
    Cpu,
    HardDrive,
    MemoryStick,
    Router,
    Wifi,
    WifiOff,
    Bluetooth,
    RadioTower,
    Satellite,
    
    // Commerce
    ShoppingCart,
    ShoppingBag,
    Store,
    CreditCard,
    Wallet,
    Coins,
    Banknote,
    Receipt,
    Tag,
    Tags,
    Package,
    PackageOpen,
    Box,
    Boxes,
    Warehouse,
    
    // Tools & Construction
    Hammer,
    Wrench,
    Screwdriver,
    Drill,
    Saw,
    Scissors,
    Ruler,
    Paintbrush,
    Palette,
    PenTool,
    Highlighter,
    Eraser,
    Brush,
    Pen,
    Pencil,
    
    // Infrastructure & Utilities
    Lightbulb,
    Lamp,
    Plug,
    Zap,
    Bolt,
    Droplet,
    Droplets,
    Water,
    Waves,
    Wind,
    Cloud,
    CloudRain,
    CloudSnow,
    CloudLightning,
    CloudFog,
    CloudDrizzle,
    Sun,
    Moon,
    Star as StarIcon,
    Sparkles,
    Thermometer,
    ThermometerSun,
    ThermometerSnowflake,
    Snowflake,
    Umbrella,
    
    // Transportation
    Car,
    Bike,
    Bus,
    Truck,
    Train,
    Ship,
    Plane,
    Navigation as NavigationIcon,
    MapPin as MapPinIcon,
    
    // Safety & Emergency
    FirstAid,
    Ambulance,
    FireExtinguisher,
    Siren,
    Megaphone,
    Bullhorn,
    Shield as ShieldIcon,
    ShieldCheck,
    
    // Health & Medical
    Stethoscope,
    HeartPulse,
    Heart,
    HeartCrack,
    Pill,
    Syringe,
    Bandage,
    Hospital,
    Building as HospitalIcon,
    
    // Environment
    TreePine,
    TreeDeciduous,
    Leaf,
    Sprout,
    Flower,
    Mountain,
    Flame,
    Fire,
    
    // Animals
    PawPrint,
    Bird,
    Fish,
    Bug,
    
    // Education
    Book,
    BookOpen,
    BookCopy,
    GraduationCap,
    School,
    Library,
    
    // Science
    Microscope,
    Beaker,
    FlaskConical,
    FlaskRound,
    TestTube,
    TestTube2,
    Atom,
    
    // Weather
    Cloudy,
    SunDim,
    Sunrise,
    Sunset,
    Tornado,
    Hurricane,
    Earthquake,
    Volcano,
    Haze,
    Wind as WindIcon,
    
    // Other
    Gamepad2,
    Trophy,
    Award,
    Medal,
    Crown,
    Target,
    Crosshair,
    Scan,
    QrCode,
    Fingerprint,
    Brain,
    Bone,
    Smile,
    Frown,
    Meh,
    
    // Aliases for common names
    Check as CheckIcon,
    X as XIcon,
    Star as StarOutline,
    Heart as HeartOutline,
    Home as HomeIcon,
    Settings as SettingsIcon,
    User as UserIcon,
    Users as UsersIcon,
    Phone as PhoneIcon,
    Mail as MailIcon,
    Camera as CameraIcon,
    Video as VideoIcon,
    Map as MapIcon,
    Globe as GlobeIcon,
    Calendar as CalendarIcon,
    Clock as ClockIcon,
    File as FileIcon,
    Folder as FolderIcon,
    Download as DownloadIcon,
    Upload as UploadIcon,
    Search as SearchIcon,
    Filter as FilterIcon,
    Edit as EditIcon,
    Trash2 as TrashIcon,
    Eye as EyeIcon,
    EyeOff as EyeOffIcon,
    Lock as LockIcon,
    Unlock as UnlockIcon,
    Key as KeyIcon,
    LogOut as LogoutIcon,
    AlertCircle as AlertCircleIcon,
    AlertTriangle as AlertTriangleIcon,
    CheckCircle as CheckCircleIcon,
    XCircle as XCircleIcon,
    Info as InfoIcon,
    HelpCircle as HelpCircleIcon,
    Bell as BellIcon,
    MessageSquare as MessageSquareIcon,
    MessageCircle as MessageCircleIcon,
    Share2 as ShareIcon,
    ThumbsUp as ThumbsUpIcon,
    ThumbsDown as ThumbsDownIcon,
    Star as StarIcon,
    Heart as HeartIcon,
    Flag as FlagIcon,
    MapPin as MapPinIcon,
    Compass as CompassIcon,
    Navigation as NavigationIcon,
    Camera as CameraIcon,
    Volume as VolumeIcon,
    Volume2 as Volume2Icon,
    Headphones as HeadphonesIcon,
    Speaker as SpeakerIcon,
    Music as MusicIcon,
    Film as FilmIcon,
    Tv as TvIcon,
    Radio as RadioIcon,
    Smartphone as SmartphoneIcon,
    Laptop as LaptopIcon,
    Monitor as MonitorIcon,
    Printer as PrinterIcon,
    Server as ServerIcon,
    Database as DatabaseIcon,
    Cpu as CpuIcon,
    HardDrive as HardDriveIcon,
    MemoryStick as MemoryStickIcon,
    Router as RouterIcon,
    Wifi as WifiIcon,
    Bluetooth as BluetoothIcon,
    RadioTower as RadioTowerIcon,
    Satellite as SatelliteIcon,
    ShoppingCart as ShoppingCartIcon,
    ShoppingBag as ShoppingBagIcon,
    Store as StoreIcon,
    CreditCard as CreditCardIcon,
    Wallet as WalletIcon,
    Package as PackageIcon,
    Hammer as HammerIcon,
    Wrench as WrenchIcon,
    Screwdriver as ScrewdriverIcon,
    Lightbulb as LightbulbIcon,
    Lamp as LampIcon,
    Plug as PlugIcon,
    Zap as ZapIcon,
    Droplet as DropletIcon,
    Water as WaterIcon,
    Cloud as CloudIcon,
    Sun as SunIcon,
    Moon as MoonIcon,
    Thermometer as ThermometerIcon,
    Snowflake as SnowflakeIcon,
    Car as CarIcon,
    Bike as BikeIcon,
    Bus as BusIcon,
    Truck as TruckIcon,
    Train as TrainIcon,
    Ship as ShipIcon,
    Plane as PlaneIcon,
    FirstAid as FirstAidIcon,
    Ambulance as AmbulanceIcon,
    Siren as SirenIcon,
    Stethoscope as StethoscopeIcon,
    HeartPulse as HeartPulseIcon,
    Pill as PillIcon,
    Syringe as SyringeIcon,
    Hospital as HospitalIcon,
    TreePine as TreePineIcon,
    Leaf as LeafIcon,
    PawPrint as PawPrintIcon,
    Book as BookIcon,
    BookOpen as BookOpenIcon,
    GraduationCap as GraduationCapIcon,
    School as SchoolIcon,
    Microscope as MicroscopeIcon,
    Beaker as BeakerIcon,
    TestTube as TestTubeIcon,
    Gamepad2 as GamepadIcon,
    Trophy as TrophyIcon,
    Award as AwardIcon,
    Crown as CrownIcon,
    Target as TargetIcon,
    Brain as BrainIcon,
    Bone as BoneIcon,
    Smile as SmileIcon,
    Frown as FrownIcon,
    Meh as MehIcon,
} from 'lucide-react';